import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic'; // Required for API routes that use headers/cookies
export const maxDuration = 300; // 5 minutes for processing multiple users

// This cron job runs 3 times daily (8am, 2pm, 8pm MST / 3pm, 9pm, 3am UTC)
// It generates auto-recommendations for users with recent activity

export async function GET(request: NextRequest) {
  try {
    // Verify this is a Vercel Cron request
    const authHeader = request.headers.get('authorization');
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    console.log('[Auto-Recommendations] Starting cron job...');

    // Create admin Supabase client
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // Get all users with auto-recommendations enabled
    const { data: userSettings } = await supabase
      .from('user_settings')
      .select('user_id, last_auto_recommendation_at, timezone')
      .eq('auto_recommendations_enabled', true);

    if (!userSettings || userSettings.length === 0) {
      console.log('[Auto-Recommendations] No users with auto-recommendations enabled');
      return NextResponse.json({
        success: true,
        message: 'No users to process',
        processed: 0,
      });
    }

    console.log(`[Auto-Recommendations] Found ${userSettings.length} users with auto-recommendations enabled`);

    const results = {
      processed: 0,
      generated: 0,
      skipped: 0,
      errors: 0,
    };

    // Process each user
    for (const settings of userSettings) {
      try {
        results.processed++;

        // Check if user had recommendations in last 7 hours (buffer for 8-hour schedule)
        const lastRecommendation = settings.last_auto_recommendation_at
          ? new Date(settings.last_auto_recommendation_at)
          : null;

        if (lastRecommendation) {
          const hoursSinceLastRecommendation =
            (Date.now() - lastRecommendation.getTime()) / (1000 * 60 * 60);

          if (hoursSinceLastRecommendation < 7) {
            console.log(
              `[Auto-Recommendations] Skipping user ${settings.user_id} - last recommendation ${hoursSinceLastRecommendation.toFixed(
                1
              )} hours ago`
            );
            results.skipped++;
            continue;
          }
        }

        // Get user's workspace
        const { data: workspaces } = await supabase
          .from('workspaces')
          .select('id')
          .eq('owner_id', settings.user_id)
          .limit(1);

        if (!workspaces || workspaces.length === 0) {
          console.log(`[Auto-Recommendations] No workspace for user ${settings.user_id}`);
          results.skipped++;
          continue;
        }

        const workspaceId = workspaces[0].id;

        // Check for recent activity (documents or insights in last 7 days)
        const sevenDaysAgo = new Date();
        sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

        const { count: recentDocuments } = await supabase
          .from('documents')
          .select('*', { count: 'exact', head: true })
          .eq('workspace_id', workspaceId)
          .gte('upload_date', sevenDaysAgo.toISOString());

        const { count: recentInsights } = await supabase
          .from('insights')
          .select('*', { count: 'exact', head: true })
          .eq('workspace_id', workspaceId)
          .gte('created_at', sevenDaysAgo.toISOString());

        if ((recentDocuments || 0) === 0 && (recentInsights || 0) === 0) {
          console.log(`[Auto-Recommendations] No recent activity for user ${settings.user_id}`);
          results.skipped++;
          continue;
        }

        console.log(
          `[Auto-Recommendations] Generating recommendations for user ${settings.user_id} (${recentDocuments} docs, ${recentInsights} insights)`
        );

        // Generate recommendations by calling the generation API endpoint internally
        const response = await fetch(
          `${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/recommendations/generate`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              // Use CRON_SECRET for service role authentication
              Authorization: `Bearer ${process.env.CRON_SECRET}`,
            },
            body: JSON.stringify({
              workspaceId,
              userId: settings.user_id,
              isAutoGenerated: true,
            }),
          }
        );

        if (!response.ok) {
          console.error(
            `[Auto-Recommendations] Failed to generate for user ${settings.user_id}:`,
            await response.text()
          );
          results.errors++;
          continue;
        }

        const data = await response.json();
        const recommendationCount = data.count || 0;

        if (recommendationCount > 0) {
          // Create in-app notification
          const { error: notificationError } = await supabase.from('notifications').insert({
            user_id: settings.user_id,
            workspace_id: workspaceId,
            type: 'recommendation',
            title: 'New Recommendations Available',
            message: `We've generated ${recommendationCount} personalized recommendations based on your recent activity.`,
            link: '/dashboard/recommendations',
            action_text: 'View Recommendations',
            metadata: {
              auto_generated: true,
              recommendation_count: recommendationCount,
            },
          });

          if (notificationError) {
            console.error(
              '[Auto-Recommendations] Failed to create notification:',
              notificationError
            );
          }

          // Send email notification if enabled
          const { data: user } = await supabase.auth.admin.getUserById(settings.user_id);

          if (user && user.user?.email) {
            // Send email using Resend
            try {
              const emailResponse = await fetch(
                `${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/notifications/email`,
                {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,
                  },
                  body: JSON.stringify({
                    to: user.user.email,
                    subject: 'New Recommendations from Vault',
                    recommendationCount,
                  }),
                }
              );

              if (!emailResponse.ok) {
                console.error(
                  '[Auto-Recommendations] Failed to send email:',
                  await emailResponse.text()
                );
              } else {
                console.log(`[Auto-Recommendations] Email sent to ${user.user.email}`);
              }
            } catch (emailError) {
              console.error('[Auto-Recommendations] Email error:', emailError);
            }
          }

          // Update last recommendation time
          await supabase
            .from('user_settings')
            .update({ last_auto_recommendation_at: new Date().toISOString() })
            .eq('user_id', settings.user_id);

          results.generated++;
          console.log(
            `[Auto-Recommendations] Successfully generated ${recommendationCount} recommendations for user ${settings.user_id}`
          );
        } else {
          results.skipped++;
          console.log(`[Auto-Recommendations] No recommendations generated for user ${settings.user_id}`);
        }
      } catch (userError) {
        console.error(`[Auto-Recommendations] Error processing user ${settings.user_id}:`, userError);
        results.errors++;
      }
    }

    console.log('[Auto-Recommendations] Cron job completed:', results);

    return NextResponse.json({
      success: true,
      results,
    });
  } catch (error) {
    console.error('[Auto-Recommendations] Cron job error:', error);
    return NextResponse.json(
      {
        error: 'Failed to run auto-recommendations',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
