import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { generateCompletion } from '@/lib/claude/client';

export const runtime = 'nodejs';
export const maxDuration = 300; // 5 minutes for batch processing

// This cron job runs daily at 7pm MST (2am UTC)
// It automatically generates insights for workspaces with activity that day

export async function GET(request: NextRequest) {
  try {
    // Verify this is a Vercel Cron request
    const authHeader = request.headers.get('authorization');
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Create admin Supabase client
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // Get today's date range (MST timezone)
    const now = new Date();
    const todayStart = new Date(now);
    todayStart.setHours(0, 0, 0, 0);
    const todayEnd = new Date(now);
    todayEnd.setHours(23, 59, 59, 999);

    console.log(`Running daily insights cron for ${todayStart.toISOString()} to ${todayEnd.toISOString()}`);

    // Find workspaces with activity today (documents uploaded or manual insights created)
    const { data: activeWorkspaces } = await supabase.rpc('get_active_workspaces_today', {
      start_date: todayStart.toISOString(),
      end_date: todayEnd.toISOString(),
    });

    // If no RPC function, fall back to manual query
    let workspacesToProcess: string[] = [];

    if (!activeWorkspaces) {
      // Get workspaces with documents uploaded today
      const { data: docsToday } = await supabase
        .from('documents')
        .select('workspace_id')
        .gte('upload_date', todayStart.toISOString())
        .lte('upload_date', todayEnd.toISOString());

      // Get workspaces with manual insights created today
      const { data: insightsToday } = await supabase
        .from('insights')
        .select('workspace_id')
        .gte('created_at', todayStart.toISOString())
        .lte('created_at', todayEnd.toISOString())
        .eq('metadata->>source', 'manual');

      // Combine and deduplicate workspace IDs
      const docWorkspaces = docsToday?.map(d => d.workspace_id) || [];
      const insightWorkspaces = insightsToday?.map(i => i.workspace_id) || [];
      workspacesToProcess = [...new Set([...docWorkspaces, ...insightWorkspaces])];
    } else {
      workspacesToProcess = activeWorkspaces;
    }

    console.log(`Found ${workspacesToProcess.length} workspaces with activity today`);

    const results = [];

    // Process each workspace
    for (const workspaceId of workspacesToProcess) {
      try {
        console.log(`Processing workspace ${workspaceId}`);

        // Get workspace details
        const { data: workspace } = await supabase
          .from('workspaces')
          .select('*')
          .eq('id', workspaceId)
          .single();

        if (!workspace) {
          console.log(`Workspace ${workspaceId} not found, skipping`);
          continue;
        }

        // Check if workspace has already generated insights today
        const metadata = (workspace.settings as any) || {};
        const today = new Date().toISOString().split('T')[0];
        const lastGeneratedDate = metadata.lastGeneratedDate;

        // Skip if already generated today
        if (lastGeneratedDate === today && metadata.dailyAutoGenerated) {
          console.log(`Workspace ${workspaceId} already had daily insights generated, skipping`);
          continue;
        }

        // Generate insights using the same logic as manual generation
        const insightsGenerated = await generateInsightsForWorkspace(supabase, workspaceId);

        if (insightsGenerated > 0) {
          // Mark as auto-generated today
          await supabase
            .from('workspaces')
            .update({
              settings: {
                ...metadata,
                lastGeneratedDate: today,
                dailyAutoGenerated: true,
              }
            })
            .eq('id', workspaceId);

          results.push({
            workspaceId,
            insightsGenerated,
            status: 'success'
          });

          console.log(`Generated ${insightsGenerated} insights for workspace ${workspaceId}`);
        }
      } catch (error) {
        console.error(`Error processing workspace ${workspaceId}:`, error);
        results.push({
          workspaceId,
          status: 'error',
          error: error instanceof Error ? error.message : 'Unknown error'
        });
      }
    }

    return NextResponse.json({
      success: true,
      processed: workspacesToProcess.length,
      results,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error('Daily insights cron error:', error);
    return NextResponse.json(
      {
        error: 'Internal server error',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

async function generateInsightsForWorkspace(supabase: any, workspaceId: string): Promise<number> {
  // Get ALL documents
  const { data: documents } = await supabase
    .from('documents')
    .select('id, title, content, upload_date')
    .eq('workspace_id', workspaceId)
    .eq('status', 'ready')
    .not('content', 'is', null)
    .order('upload_date', { ascending: false });

  // Get ALL existing insights
  const { data: existingInsights } = await supabase
    .from('insights')
    .select('id, type, title, content, created_at, metadata')
    .eq('workspace_id', workspaceId)
    .order('created_at', { ascending: false });

  if ((!documents || documents.length === 0) && (!existingInsights || existingInsights.length === 0)) {
    console.log(`No content to analyze for workspace ${workspaceId}`);
    return 0;
  }

  // Prepare document summaries
  const documentSummaries = (documents || []).map((doc: any, index: number) => {
    const uploadDate = new Date(doc.upload_date);
    const now = new Date();
    const daysAgo = Math.floor((now.getTime() - uploadDate.getTime()) / (1000 * 60 * 60 * 24));

    return {
      title: doc.title,
      preview: doc.content?.slice(0, 3000),
      uploadDate: doc.upload_date,
      daysAgo,
      isRecent: daysAgo <= 1,
      position: index + 1,
    };
  });

  // Prepare insight summaries
  const insightSummaries = (existingInsights || []).map((insight: any) => ({
    type: insight.type,
    title: insight.title,
    content: insight.content,
    source: (insight.metadata as any)?.source || 'unknown',
    createdAt: insight.created_at,
  }));

  // Build context
  let contextText = '';

  if (documents && documents.length > 0) {
    const recentDocs = documentSummaries.filter((d: any) => d.isRecent);
    contextText += `Documents in workspace (${documents.length} total - ${recentDocs.length} uploaded recently):\n`;
    contextText += `**NOTE: This is an automatic daily summary. Focus on what was added or updated today.**\n\n`;

    contextText += documentSummaries.map((doc: any) => {
      const recencyLabel = doc.isRecent ? 'RECENT - uploaded today/yesterday' : `${doc.daysAgo} days ago`;
      return `${doc.position}. "${doc.title}" (${recencyLabel})\n   Content: ${doc.preview}${doc.preview && doc.preview.length >= 3000 ? '...' : ''}`;
    }).join('\n\n');
    contextText += '\n\n';
  }

  if (existingInsights && existingInsights.length > 0) {
    const manualInsights = insightSummaries.filter((i: any) => i.source === 'manual');
    contextText += `Existing Insights (${existingInsights.length} total - ${manualInsights.length} manual from user):\n\n`;

    contextText += insightSummaries.map((insight: any, i: number) =>
      `${i + 1}. [${insight.type.toUpperCase()}] "${insight.title}"\n   Content: ${insight.content}\n   Source: ${insight.source === 'manual' ? 'Manual (user-created)' : 'AI-generated'}`
    ).join('\n\n');
  }

  const prompt = `You are generating automatic daily insights for a user's continual memory system.

${contextText}

Generate 2-3 insights that:
1. Summarize what was added or updated today
2. Identify patterns across ALL documents and insights
3. Provide smart recommendations based on the user's interests and patterns
4. Suggest next steps, tasks, or reminders based on the content
5. Offer "you may like" suggestions for related topics to explore
6. Connect new information to existing knowledge

**Types of Insights to Include:**
- **suggestion**: "Based on your interest in X, you may want to explore Y" or actionable next steps
- **reminder**: Deadlines, follow-ups, or action items mentioned in today's content
- **pattern**: Recurring themes that emerged today or connect to historical content
- **trend**: How today's content relates to or changes previous understanding
- **contradiction**: Conflicting information that needs attention

Focus on making these insights actionable and valuable for the user's daily workflow. Be proactive in suggesting tasks and related topics.

Respond with a JSON array:
[
  {
    "type": "pattern" | "contradiction" | "suggestion" | "reminder" | "trend",
    "title": "Concise title (max 100 chars)",
    "content": "Detailed explanation (200-500 chars)",
    "priority": 1-100,
    "relatedDocumentTitles": ["doc title 1", "doc title 2"]
  }
]`;

  const aiResponse = await generateCompletion(
    [{ role: 'user', content: prompt }],
    {
      maxTokens: 2000,
      temperature: 0.7,
      system: 'You are a helpful AI assistant. Always respond with valid JSON only.',
    }
  );

  // Parse AI response
  let generatedInsights;
  try {
    const jsonMatch = aiResponse.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      throw new Error('No JSON found in response');
    }
    generatedInsights = JSON.parse(jsonMatch[0]);
  } catch (parseError) {
    console.error('Failed to parse AI response for workspace', workspaceId);
    return 0;
  }

  // Create document title to ID mapping
  const titleToId = new Map((documents || []).map((doc: any) => [doc.title, doc.id]));
  const validTypes = ['pattern', 'contradiction', 'suggestion', 'reminder', 'trend'];

  // Insert insights
  const insightsToInsert = generatedInsights
    .filter((insight: any) => validTypes.includes(insight.type))
    .map((insight: any) => {
      const relatedDocIds = (insight.relatedDocumentTitles || [])
        .map((title: string) => titleToId.get(title))
        .filter((id: string | undefined): id is string => id !== null && id !== undefined);

      return {
        workspace_id: workspaceId,
        type: insight.type,
        title: insight.title?.slice(0, 200) || 'Daily Insight',
        content: insight.content?.slice(0, 2000) || '',
        priority: Math.min(100, Math.max(1, insight.priority || 50)),
        status: 'new',
        metadata: {
          source: 'ai_generated',
          generated_at: new Date().toISOString(),
          model: 'gpt-4',
          auto_daily: true,
        },
        related_documents: relatedDocIds,
      };
    });

  if (insightsToInsert.length === 0) {
    return 0;
  }

  const { data: createdInsights, error } = await supabase
    .from('insights')
    .insert(insightsToInsert)
    .select();

  if (error) {
    console.error('Error inserting daily insights:', error);
    return 0;
  }

  return createdInsights?.length || 0;
}
